<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-DedupeWaterfall.Orchestrator-dc71e65e-818b-4af6-b576-067d84184171</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DedupeWaterfall.Core\DedupeWaterfall.Core.csproj" />
    <ProjectReference Include="..\DedupeWaterfall.Data\DedupeWaterfall.Data.csproj" />
  </ItemGroup>
</Project>
